version: "3"

name: logdrop

services:
  db:
    image: postgres:latest
    container_name: logdrop-db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: logdrop
    volumes:
      - logdrop-data:/postgres/data
    ports:
      - 5432:5432
volumes:
  logdrop-data:
    driver: local
